Improve Windows Compatibility
JTPond/calcifyarchive pull request #1
Opened 2021-02-16 03:39 UTC by duytnguyendtn

The goal of this PR is two fold:

1. With Command Prompt being deprecated by Microsoft, introduce a build script using Powershell
2. TODO: Fix a bug in the Batch script, where a wildcard copy isn't moving files over properly

2021-06-30 03:07 UTC, duytnguyendtn commented
NOTE @JTPond: This PR also includes the behavior described in #2. Figured if it ends up being a real bug, a new PR should address that, but for this PR, `build.ps1` follows the behavior of `build.bat` and `build.sh`

2021-06-30 03:44 UTC, JTPond requested changes
I don't see any need for a new PR. I'm not running a tight ship here. If you can just add the changes from the issue, I will approve.

2021-07-01 03:31 UTC, duytnguyendtn commented
Alrighty! Added two commits that fixes #2 for both `build.bat` and `build.ps1`

2021-07-01 13:17 UTC, JTPond approved these changes

2021-07-01 13:17 UTC, merged